# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(blank=True, verbose_name='消息')),
                ('status', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, default='images/default.jpg', upload_to='images', verbose_name='头像')),
                ('sex', models.CharField(blank=True, choices=[('男', '♂'), ('女', '♀')], max_length=2, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, default='2000-01-01', verbose_name='生日')),
                ('school', models.TextField(default='暂未设置所在学校', max_length=50, verbose_name='学校')),
                ('autograph', models.TextField(default='暂未设置个性签名', max_length=50, verbose_name='个性签名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YZM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yzm', models.IntegerField(blank=True, default=123456)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
