# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='picture',
            new_name='pic',
        ),
        migrations.AddField(
            model_name='user_info',
            name='adress',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_info',
            name='autograph',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_info',
            name='sex',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
