# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yzm',
            name='user',
        ),
        migrations.AddField(
            model_name='yzm',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
