# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170705_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='adress',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='autograph',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
