# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170705_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='owner',
            new_name='user',
        ),
    ]
