# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170706_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='sex',
            field=models.CharField(choices=[('男', '♂'), ('女', '♀')], max_length=2),
        ),
    ]
