# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20170904_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='focus',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='focus', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
