# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_follower_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='focus',
        ),
    ]
