# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_remove_follower_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='owner',
        ),
        migrations.AddField(
            model_name='follower',
            name='focus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='focus', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
