# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170814_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name=''),
        ),
    ]
