# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_theme_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='display',
            new_name='设为私密',
        ),
    ]
