# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20170810_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='belong',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
