# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20170810_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
