# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20170922_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='写下....'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=20, verbose_name='标题'),
        ),
    ]
