# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20171002_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
