# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('text', models.TextField(verbose_name='正文')),
                ('date_setup', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
