# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
